# Generated by Django 5.1.3 on 2024-11-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypoll', '0002_alter_poll_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='time',
        ),
    ]
