# Generated by Django 5.1.3 on 2024-11-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypoll', '0003_remove_poll_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='author',
            field=models.CharField(default='mal', max_length=100),
        ),
        migrations.AddField(
            model_name='poll',
            name='categories',
            field=models.CharField(default='Mal', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='post',
            field=models.TextField(default='Cat', max_length=1000),
        ),
        migrations.AlterField(
            model_name='poll',
            name='tag',
            field=models.CharField(default='Cat', max_length=20, unique=True),
        ),
    ]
