# Generated by Django 5.1.3 on 2024-11-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypoll', '0004_poll_author_poll_categories_poll_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='poll',
            name='categories',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='post',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='poll',
            name='tag',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
