# Generated by Django 5.1.3 on 2024-11-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypoll', '0005_alter_poll_author_alter_poll_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='categories',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='poll',
            name='tag',
            field=models.CharField(max_length=20),
        ),
    ]
